[colors]
black = #32344a
blue = #7aa2f7
cyan = #449dab
green = #9ece6a
magenta = #ad8ee6
red = #f7768e
white = #787c99
yellow = #e0af68
background_color = #1a1b26
foreground_color = #a9b1d6


;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = ${colors.background_color}
background-alt = ${colors.blue}
foreground = ${colors.foreground_color}
primary = ${colors.blue}
secondary = ${colors.cyan}
alert = ${colors.red}
disabled = ${colors.white}
enabled = ${colors.green}


[bar/toph]
monitor = ${env:MONITOR:}
width = 100%
height = 28pt
radius = 0

; dpi = 96

background = ${colors.background_color}
foreground = ${colors.foreground_color}

bottom = false

line-size = 6pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = ""
separator-foreground = ${colors.flamingo}

font-0 = CommitMono Nerd Font Mono:size=14;6
font-1 = CommitMono Nerd Font Mono:size=20;6

# Module layout
modules-left = xworkspaces
modules-center = date
modules-right =  pulseaudio wlan bluetooth battery fullcharge

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = 
label-active-foreground = ${colors.primary}
label-active-padding = 1

label-occupied = 
label-occupied-foreground = ${colors.primary}
label-occupied-padding = 1

label-urgent = 
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = 
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh show_bluetooth_status
interval = 5

click-right = ~/.config/polybar/scripts/bluetooth.sh launch_applet
click-left = ~/.config/polybar/scripts/bluetooth.sh toggle_bluetooth

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
bar-volume-width = 9

label-volume = vol: %percentage%%
label-volume-foreground = ${colors.primary}

label-muted = MUTED
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background_color}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/battery]
type = internal/battery
format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}
full-at = 99

format-full = %{A1:~/.config/i3/scripts/powermenu:}<ramp-capacity>%{A1}

format-charging = %{A1:~/.config/i3/scripts/powermenu:}<animation-charging> <label-charging>%{A1}
format-charging-foreground = ${colors.primary}
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

; Framerate in milliseconds
animation-charging-framerate = 750
animation-charging-foreground = ${colors.primary}
# add <label-discharging> for percentage
format-discharging = %{A1:~/.config/i3/scripts/powermenu:}<ramp-capacity>%{A}
format-discharging-foreground = ${colors.primary}
label-discharging-foreground = ${colors.foreground_color}
label-charging-foreground = ${colors.primary}
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

ramp-capacity-0-foreground = ${colors.alert}
ramp-capacity-1-foreground = ${colors.yellow}
ramp-capacity-4-foreground = ${colors.green}

battery = BAT0
adapter = AC
poll-interval = 5

format-low = %{A1:~/.config/i3/scripts/powermenu:}<animation-low>{%A1}

low-at = 5
animation-low-0-foreground = ${colors.alert}
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[network-base]
type = internal/network
interval = 5
format-connected = %{A1:~/.local/bin/rofi-wifi-menu.sh:}<ramp-signal>%{A1}
format-disconnected = %{A1:~/.local/bin/rofi-wifi-menu.sh:}<label-disconnected>%{A1}

label-disconnected = 󰤫
label-disconnected-foreground = ${colors.disabled}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %essid%

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

ramp-signal-foreground = ${colors.primary}
click-left = "#wlan.hook-0"

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = " %H:%M"
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/fullcharge]
type = custom/script
exec = if [ "$(cat /sys/class/power_supply/BAT0/charge_stop_threshold)" -eq 100 ]; then echo "⚡"; else echo ""; fi
interval = 10

format-foreground = ${colors.green}

; Left click → revert script
click-left = ~/.local/bin/disable-full-charge.sh

