
unbind r
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"
set -g prefix C-Space

# Keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Cursor
set -g cursor-style blinking-bar

# Plugins
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Keep tpm at the end
run '~/.tmux/plugins/tpm/tpm'

